Реализован выбор позиции дерева.
Yekaterinburg-Tree-Map/ekbtrees-android pull request #11
Opened 2021-05-18 14:18 UTC by IlyaDeryabin

Добавлен фрагмент редактирования информации о дереве (дополняться будет последующих итерациях).
Также добавлен экран краткой информации о дереве (будет дополняться) с кнопкой для перехода к фрагменту детализации.

2021-05-25 14:55 UTC, R00We requested changes

2021-05-25 18:04 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/ui/edittree/EditTreeFragment.kt
> +    private lateinit var viewModel: EditTreeViewModel
Делегаты наше всё
```kotlin
// tree map fragment
private val treeMapViewModel: TreeMapViewModel by viewModels()

// edit tree fragment
private val viewModel: EditTreeViewModel by viewModels()
```

2021-05-25 18:06 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/ui/map/TreeMapFragment.kt
> +            treeMapViewModel.treeDataState.collect { treeDataViewState ->
Сказано - сделано.

2021-05-25 18:14 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/ui/map/TreeMapFragment.kt
> +                        else View.GONE
Показ / сокрытие View элементов вынес в отдельные методы:
```kotlin
private fun showViews() { }
```
```kotlin
private fun hideViews() { }
```
Данные методы вызываются в нужных стейтах внутри ```when```

2021-05-25 18:34 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/ui/intent/TreeMapIntent.kt
> +sealed class TreeMapIntent {
Каждый интент снабжён краткой информацией и переименован в соответствии с его сутью.

2021-05-28 11:17 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/ui/map/TreeMapViewModel.kt
> +    val treeDataState: StateFlow<TreesViewState> = _treeDataState.asStateFlow()
Создал BaseViewModel и TreeMapContract для общения между фрагментом и его ViewModel.

2021-05-28 11:18 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/ui/map/TreeMapFragment.kt
> +                treeMapViewModel.intent.send(TreeMapIntent.RequestMapState)
Сделано.

2021-06-01 05:07 UTC, R00We approved these changes

2021-06-01 05:08 UTC, R00We commented
На созвоне порешаем конфликты и зальем в main ветку

2021-06-02 05:06 UTC, merged