#10 add tree detail
Yekaterinburg-Tree-Map/ekbtrees-android pull request #14
Opened 2021-06-08 18:32 UTC by dienyaaa

Добавлен экран Деталей дерева
Не хватает полей для вывода в карточке: Фото, высоты, числа стволов и многих, взятых из Сущности дерева

2021-06-15 04:59 UTC, R00We commented
Увидел что mr закрыл и далее делал доработки. Код пока не смотрю, отсмотрю с доработками

2021-06-18 09:37 UTC, R00We requested changes

2021-06-18 09:37 UTC, R00We commented on app/build.gradle
> +    implementation 'com.beust:klaxon:5.5'
Предлагаю использовать либо `Gson` либо `kotlinx.serialization`

2021-06-18 09:37 UTC, R00We commented on app/src/main/java/ru/ekbtrees/treemap/ui/treedetail/TreeDetailFragment.kt
> +        parsedTree = Klaxon().parse<TreeEntity>(stringifiedTree)!!
Для передачи сущностей между экранами их нада сделать `Parcelable` и так же складывать в bundle. Есть специальный генератор который упрощает работу https://developer.android.com/kotlin/parcelize

2021-06-18 09:37 UTC, R00We commented on app/src/main/java/ru/ekbtrees/treemap/ui/treedetail/TreeDetailFragment.kt
> +        observeViewModel()
Нада унести в `onViewCreted` иначе при сворачивании приложения будет повторная подписка происходить

2021-07-02 19:21 UTC, IlyaDeryabin requested changes

2021-07-02 19:21 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/ui/treedetail/TreeDetailViewModel.kt
> +        setState(TreeDetailContract.TreeDetailState.Loaded(instanceValue))
Для получения детализации дерева с сервера достаточно знать `TreeId`. Рекомендую переименовать метод в `provideTreeId` и изменить аргумент на `treeId: String`.

2021-07-02 19:21 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/ui/treedetail/TreeDetailFragment.kt
> +        fun newInstance(treeEntity: TreeEntity) =
Возвращай `TreeId` в аргумент.

2021-07-05 19:03 UTC, IlyaDeryabin requested changes
Исправь эти недоработки и будем считать, что задачу ты выполнил.

2021-07-06 03:36 UTC, IlyaDeryabin approved these changes
lgtm

2021-07-14 14:40 UTC, merged