#20 Добавить выгрузку деревьев и кластеров из сервера
Yekaterinburg-Tree-Map/ekbtrees-android pull request #22
Opened 2021-07-21 15:40 UTC by IlyaDeryabin

2021-07-28 14:50 UTC, R00We requested changes

2021-07-28 14:50 UTC, R00We commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +            clusterTreesEntityList.add(ClusterTreeDtoMapper().map(clusterTreesDto))
На каждый проход создается мапер. Создание предлагаю вынести из цикла

2021-07-28 14:50 UTC, R00We commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +        TreesRepositoryImpl::class.simpleName
лишнее

2021-07-28 14:50 UTC, R00We commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +            TreesRepositoryImpl::class.simpleName
лишнее

2021-07-28 14:50 UTC, R00We commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +        if (!::species.isInitialized) {
лучше `species` `nullable` сделать раз необходима такая проверка

2021-07-28 14:50 UTC, R00We commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +                i++
вместо этого лучше использовать `forEachIndexed`

2021-07-28 14:50 UTC, R00We commented on app/src/main/java/ru/ekbtrees/treemap/data/api/TreesApiService.kt
> +    @GET("api/trees-cluster/get-in-region")
'api/' часть лучше в `baseUrl` унести

2021-07-28 16:14 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +            clusterTreesEntityList.add(ClusterTreeDtoMapper().map(clusterTreesDto))
Вынес создание мапера из цикла

2021-07-28 16:14 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +        TreesRepositoryImpl::class.simpleName
Удалил

2021-07-28 16:14 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +            TreesRepositoryImpl::class.simpleName
Удалил

2021-07-28 16:16 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +        if (!::species.isInitialized) {
Сделал nullable

2021-07-28 16:16 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/data/TreesRepositoryImpl.kt
> +                i++
Забыл про `forEachIndexed`. Исправил.

2021-07-28 16:17 UTC, IlyaDeryabin commented on app/src/main/java/ru/ekbtrees/treemap/data/api/TreesApiService.kt
> +    @GET("api/trees-cluster/get-in-region")
Унёс.

2021-08-01 16:49 UTC, R00We approved these changes

2021-08-01 16:49 UTC, merged